// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package libcentrifugo

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

var _ = json.RawMessage{} // suppress unused package warning

func easyjson_decode_github_com_centrifugal_centrifugo_libcentrifugo_ClientMessageResponse(in *jlexer.Lexer, out *ClientMessageResponse) {
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "method":
			out.Method = string(in.String())
		case "body":
			(out.Body).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
func easyjson_encode_github_com_centrifugal_centrifugo_libcentrifugo_ClientMessageResponse(out *jwriter.Writer, in *ClientMessageResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"method\":")
	out.String(string(in.Method))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"body\":")
	(in.Body).MarshalEasyJSON(out)
	out.RawByte('}')
}
func (v *ClientMessageResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson_encode_github_com_centrifugal_centrifugo_libcentrifugo_ClientMessageResponse(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}
func (v *ClientMessageResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson_encode_github_com_centrifugal_centrifugo_libcentrifugo_ClientMessageResponse(w, v)
}
func (v *ClientMessageResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson_decode_github_com_centrifugal_centrifugo_libcentrifugo_ClientMessageResponse(&r, v)
	return r.Error()
}
func (v *ClientMessageResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson_decode_github_com_centrifugal_centrifugo_libcentrifugo_ClientMessageResponse(l, v)
}
